### ISSUE TITLE
MAKE IT MORE DYNAMIC pls :)

### ISSUE THREAD

**Issue by DevShaded** [TheSaintLeon/LampSetup#1]
Let me choose what database username, password, and database name, please. I would rather not have to edit the script to change it. Please fix thanks.

**Comment by TheSaintLeon** [comment]
Ok boss, I fix for you later. Give me some time :)

**Comment by DevShaded** [comment]
I would fix this in 2ms, but I don't do works for minorities in europe.

**Comment by DevShaded** [comment]
Will this be fixed soon?

**Comment by TheSaintLeon** [comment]
Yes! Give me a little bit :)

**Comment by DevShaded** [comment]
OK

**Comment by DevShaded** [comment]
pls fix it now

**Comment by TheSaintLeon** [comment]
Okay sir :) I fixed the
